server:
  port: 1337
spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/text_generator
    username: postgres
    password: postgres
  flyway:
    locations: classpath:db/migration
  thymeleaf:
    cache: false
